### ISSUE TITLE
PA fixes for Audrey and amixer

### ISSUE THREAD

**Issue by pmatis** [hollie/misterhouse#330]
H Plato discovered a few odd things.

With the amixer PA type, not specifying the full mixer details (e.g, 'front:0"), a comma is used anyhow.

With Audrey, no web_hook is created, since the wrong test is used to see if an Audrey zone is used.

**Comment by hollie** [comment]
See pull request #619

**Comment by hollie** [comment]
Fix is merged into master. Will be released in v4.2
