### ISSUE TITLE
X10 CM15A documentation on github doesn't show in browswer

### ISSUE THREAD

**Issue by fredrikoh** [hollie/misterhouse#484]
New to GitHub, returning Misterhouse user after a pause of order of 10 years.
I would like to read the wiki doc X10 CM15A but get an "error rendering this page" both on IE Explorer and Firefox.  I would really need some guidance on how to get the CM15 to work with MisterHouse.

Fredrik

**Comment by hollie** [comment]
Hey @frederikoh,

thanks for the bug report. I have made an initial fix to the page so that it at least renders. Not all formatting is completely fixed, though. If you find the info on the page useful, feel free to adapt the formatting.

Best regards,
 Lieven.

**Comment by fredrikoh** [comment]
Thanks for fixing the page.  I hope I will now be more successful in getting mh up an running on my raspberrypi...
Greetings,Fredrik
 

     Den söndag, 11 januari 2015 20:29 skrev Lieven Hollevoet <notifications@github.com>:
   

 Closed #484.—
