### ISSUE TITLE
insteon: $kpl->level returns off or on, not the actual percentage, but $lamp->level works

### ISSUE THREAD

**Issue by marcmerlin** [hollie/misterhouse#494]
Status request on a KPL dimmer does return the correct percentage, but then it gets lost and changed to off or on depending on the percentage.

This device:
INSTEON_KEYPADLINC,     0E.07.49:01,    fmr_kpl,        All_Lights|fmr_all # v2.0 keypadlinc dimmer dual band

status request returns:
[Insteon::BaseObject] $fmr_kpl::set_receive(19%, $PLM)

But printing from code fails, although printing a linked lamplinc shows the percentage
    print $fmr_kpl->state." | ";
    print $fmr_kpl->level." | ";
    print $fmr_lamp->level." | ";
returns:
off | 100 | 19

**Comment by spencerryan** [comment]
My Perl is rusty, but something in Lighting.pm inside package Insteon::KeyPadLinc there is logic to only get dimming values on group 01 (which is the local load). Unfortunately the parent class SUPER inheritance isn't working correctly and is calling the wrong function.

Replace this line:
` return $self->SUPER::derive_link_state($p_state);`
With this:
` return $self->Insteon::DimmableLight::derive_link_state($p_state);`

Which will correctly return on level, and let you properly use on_fast and off_fast if you so desire.

**Comment by marcmerlin** [comment]
thanks, that's helpful

**Comment by marcmerlin** [comment]
Thanks @spencerryan , tested and merged. Sorry for the delay.
