### ISSUE TITLE
IA7 collections.json default location

### ISSUE THREAD

**Issue by hollie** [hollie/misterhouse#518]
Hello,

the default search location for the IA7 config is ```local/data/web```. This is maybe not the best location to put it, as this folder typically contains info that is not put under revision control. The data folder is the location where MisterHouse stores results from operations like e.g. fetching a web page.

For previous web interfaces, there was a mh.private.ini parameter called 'html_alias_web' that you could use to put custom shtml files under to configure the web interface.

Would it not be a good idea to apply the same principle for the collections.json file to configure the IA7 interface? This way, the collections.json file would be stored in a folder that is typically also put under version control by the user.

Users could then also put custom shtml files like the sample.shtml file in that folder. All web-related configuration files would then be present in a single location.

Regards,
 Lieven.

**Comment by hplato** [comment]
Hi,

  Good idea. Since the html_alias stuff is in http_server.pl, you should be able to create an alias and then point a collection item to the new spot, without any changes to the existing setup. I have one custom file, I’ll try this out see if any problems crop up.

**Comment by hollie** [comment]
Hey @hplato 

actually I tried this out just now. Seems to be working fine, so this ticket can be closed for me.

Best regards,
 Lieven.

**Comment by hplato** [comment]
Thanks Lieven. If you have a chance want to add it to the wiki. Probably a good thing for folks to know when they first set things up?

**Comment by hollie** [comment]
Done, added the info to the wiki.
