### ISSUE TITLE
Unable to address Keypadlinc buttons

### ISSUE THREAD

**Issue by Gribnif** [hollie/misterhouse#535]
Before the (semi)recent changes in master having to do with intra-device Insteon links, I'm pretty sure I was able to use surrogates and write code that would address the buttons of a Keypadlinc directly, to turn them on or off. Now, either I'm not understanding something, or this ability is missing.

Here's my config for one KPL device, which is attached to a Fanlinc and uses the four small buttons to set fan speed:

INSTEON_KEYPADLINCRELAY, 34.65.99:01, guest_kp,          Second_Floor|Slaves
INSTEON_KEYPADLINCRELAY, 34.65.99:03, guest_b1,          Second_Floor
INSTEON_KEYPADLINCRELAY, 34.65.99:04, guest_b2,          Second_Floor
INSTEON_KEYPADLINCRELAY, 34.65.99:05, guest_b3,          Second_Floor
INSTEON_KEYPADLINCRELAY, 34.65.99:06, guest_b4,          Second_Floor
INSTEON_FANLINC,         32.35.05:01, guest_fl_light,    Second_Floor|Masters
INSTEON_FANLINC,         32.35.05:02, guest_fl_fan,      Room_Fans

SCENE_MEMBER, guest_fl_fan,   guest_b1,       100%, 0s
SCENE_MEMBER, guest_fl_fan,   guest_b2,       51%, 0s
SCENE_MEMBER, guest_fl_fan,   guest_b3,       25%, 0s
SCENE_MEMBER, guest_fl_fan,   guest_b4,       0%, 0s
SCENE_MEMBER, guest_kp,       guest_fl_light, 100%, 0s
SCENE_MEMBER, guest_fl_light, guest_kp,       100%, 0s
SCENE_BUILD, surrogate_guest, guest_b1, 1, 1, 0%
SCENE_BUILD, surrogate_guest, guest_b2, 1, 1, 0%
SCENE_BUILD, surrogate_guest, guest_b3, 1, 1, 0%
SCENE_BUILD, surrogate_guest, guest_b4, 1, 1, 0%

I want to be able to turn off the fan in code and also turn off all buttons (or, better yet, turn on just guest_b4), but can't figure out how. There doesn't seem to be a $surrogate_guest object. Using:

$guest_b4->set(ON)

returns the error, "You may not directly attempt to set a keypadlinc's button unless you have defined a reverse link with the "surrogate" keyword". But the "surrogate" keyword isn't used anymore, as far as I can tell.

**Comment by drobinson0919** [comment]
Create a PLM scene, link the button to the scene, controlling the scene
will change the button state.

**Comment by Gribnif** [comment]
Yes, that worked. Seems obvious now.

**Comment by drobinson0919** [comment]
obvious that they should be treated differently than everything else?
