### ISSUE TITLE
Obsolete Perl modules break interface to external web appliances

### ISSUE THREAD

**Issue by bpmartin20** [hollie/misterhouse#553]
I wrote a Perl module to interface with my Venstar Colortouch T7850 thermostat's web interface.  It works great outside of MH, but wouldn't work when called from my MH code.  It took me about a week and a half to track it down.  It turns out that we've got some really old versions of some Perl modules included with Misterhouse.  They're particularly weak in the are of SSL connections (and in fact the API interface has changed between the version included in MH and the current version on CPAN).  I resolved my problem by renaming the following directories in MH to add a ".orig" suffix -- all are in lib/site:

HTML
HTTP
LWP
LWP.pm
NET
URI

This allowed me to use the more current versions on the system to set up an SSL connection to the Venstar web interface.  I didn't change any MH code, so MH on my system is now using the newer modules, too.  I've seen no impact at all to MH, although I don't use the web interface a lot.

What are our options for removing these from the Git tree and letting MH and any user code in it find the versions in the regular system Perl libraries?  If we can't do that, how about renaming the old versions (e.g. MHHTML, MHLWP) and making the matching adjustments in the MH code, so that user code running in MH that needs more current versions can access them, and MH can still use the old versions?

Thank you for considering this.

**Comment by hplato** [comment]
Good points. I’d suggest we leave as is for the v4 release (since the window is short), but this could be a good task for the v4.1 update.

As an aside, does the T7850 have the local web server option? I wonder if it works with the T5900 module I put together. I’ve been using it successfully to control humidity, track state, turn schedules on and off…

**Comment by bpmartin20** [comment]
I'm not sure I quite follow your question, but I'll take a stab at 
answering it.

The T7850 doesn't have a web page, in that there's nothing there that's 
presentable to normal user.  The API is accessible via HTTP, however.  
For example, when I visit the main "page" for it I receive:

{"api_ver":5,"type":"residential"}

I wrote the code based on the vendor's "ColorTouch Remote Control 
Protocol 
<http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf>" 
document, which doesn't appear to be specific to any particular models.  
Since the T5900 is a ColorTouch thermostat, I think my code should work 
just as well there.

                                 -B.


On 11/01/2015 06:46 PM, hplato wrote:
> Good points. I’d suggest we leave as is for the v4 release (since the 
> window is short), but this could be a good task for the v4.1 update.
>
> As an aside, does the T7850 have the local web server option? I wonder 
> if it works with the T5900 module I put together. I’ve been using it 
> successfully to control humidity, track state, turn schedules on and off…
>
>
> > On Nov 1, 2015, at 7:40 PM, Brian P. Martin 
> <notifications@github.com> wrote:
> >
> > I wrote a Perl module to interface with my Venstar Colortouch T7850 
> thermostat's web interface. It works great outside of MH, but wouldn't 
> work when called from my MH code. It took me about a week and a half 
> to track it down. It turns out that we've got some really old versions 
> of some Perl modules included with Misterhouse. They're particularly 
> weak in the are of SSL connections (and in fact the API interface has 
> changed between the version included in MH and the current version on 
> CPAN). I resolved my problem by renaming the following directories in 
> MH to add a ".orig" suffix -- all are in lib/site:
> >
> > HTML
> > HTTP
> > LWP
> > LWP.pm
> > NET
> > URI
> >
> > This allowed me to use the more current versions on the system to 
> set up an SSL connection to the Venstar web interface. I didn't change 
> any MH code, so MH on my system is now using the newer modules, too. 
> I've seen no impact at all to MH, although I don't use the web 
> interface a lot.
> >
> > What are our options for removing these from the Git tree and 
> letting MH and any user code in it find the versions in the regular 
> system Perl libraries? If we can't do that, how about renaming the old 
> versions (e.g. MHHTML, MHLWP) and making the matching adjustments in 
> the MH code, so that user code running in MH that needs more current 
> versions can access them, and MH can still use the old versions?
> >
> > Thank you for considering this.
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/hollie/misterhouse/issues/553>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367>.
>


-- 
--------------------
Brian P. Martin, Chief Consultant
Martin Consulting Services, Inc.
Phone: 503-617-4500
E-mail: Brian@MartinConsulting.com
Web: www.martinconsulting.com
Blog: www.pdxsys.com

**Comment by hplato** [comment]
Yes, similar to my T5900. I’m just curious if that module I developed works with a later version. I set this up to access the local web server as I didn’t want to rely on the external ‘sky port’ cloud service.

The T5900 is api level 4, so I don’t know if that changes anything. For example my user user code:

use Venstar_Colortouch;

$thermostat_main = new Venstar_Colortouch(‘123.123.123.123',10);
$thermostat_main_temp = new Venstar_Colortouch_Temp($thermostat_main);
$thermostat_main_fan = new Venstar_Colortouch_Fan($thermostat_main);
$thermostat_main_schedule = new Venstar_Colortouch_Schedule($thermostat_main);
$thermostat_main_hum = new Venstar_Colortouch_Humidity($thermostat_main);
$thermostat_main_hum_sp = new Venstar_Colortouch_Humidity_sp($thermostat_main);
$thermostat_main_comm = new Venstar_Colortouch_Comm($thermostat_main);

I get these details when I start up MH:

0/17/15 02:30:34 PM [Venstar Colortouch] Residental Venstar ColorTouch found with api level 4
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Data Successfully Retrieved
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Device Main is a heating only Thermostat
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Fan mode is set to auto
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Fan is currently off
10/17/15 02:30:34 PM [Venstar Colortouch:Main] System mode is heating
10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is idle
10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is on a schedule
10/17/15 02:30:34 PM [Venstar Colortouch:Main] System schedule is day (occupied2)
10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is currently on home mode
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Temperature: 23.5C
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Humidity:30%
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Setpoint	Min	Max
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Heat:	22C		1.5C	37C
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Cool:	29.5C		1.5C	37C
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Humidity:	40%
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Setpoint Delta: 2C
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Thermostat Sensor Temperature:23.5C
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Thermostat Sensor Humidity:30%
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Outdoor Temperature Sensor not connected
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering temp child object
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering fanstate child object
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering sched child object
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering hum child object
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering hum_sp child object
10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering comm child object

**Comment by bpmartin20** [comment]
I looked at your module, but didn't try it out because it didn't appear 
to support SSL.   From what I saw of it, though, it's a lot better code 
than mine.

      -B.

On 11/01/2015 08:00 PM, hplato wrote:
> Yes, similar to my T5900. I’m just curious if that module I developed 
> works with a later version. I set this up to access the local web 
> server as I didn’t want to rely on the external ‘sky port’ cloud service.
>
> The T5900 is api level 4, so I don’t know if that changes anything. 
> For example my user user code:
>
> use Venstar_Colortouch;
>
> $thermostat_main = new Venstar_Colortouch(‘123.123.123.123',10);
> $thermostat_main_temp = new Venstar_Colortouch_Temp($thermostat_main);
> $thermostat_main_fan = new Venstar_Colortouch_Fan($thermostat_main);
> $thermostat_main_schedule = new 
> Venstar_Colortouch_Schedule($thermostat_main);
> $thermostat_main_hum = new Venstar_Colortouch_Humidity($thermostat_main);
> $thermostat_main_hum_sp = new 
> Venstar_Colortouch_Humidity_sp($thermostat_main);
> $thermostat_main_comm = new Venstar_Colortouch_Comm($thermostat_main);
>
> I get these details when I start up MH:
>
> 0/17/15 02:30:34 PM [Venstar Colortouch] Residental Venstar ColorTouch 
> found with api level 4
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Data Successfully Retrieved
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Device Main is a 
> heating only Thermostat
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Fan mode is set to auto
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Fan is currently off
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System mode is heating
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is idle
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is on a schedule
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System schedule is day 
> (occupied2)
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is currently on 
> home mode
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Temperature: 23.5C
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Humidity:30%
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Setpoint Min Max
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Heat: 22C 1.5C 37C
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Cool: 29.5C 1.5C 37C
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Humidity: 40%
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Setpoint Delta: 2C
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Thermostat 
> Sensor Temperature:23.5C
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Thermostat 
> Sensor Humidity:30%
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Outdoor Temperature 
> Sensor not connected
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering temp child 
> object
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering fanstate 
> child object
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering sched child 
> object
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering hum child 
> object
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering hum_sp 
> child object
> 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering comm child 
> object
>
>
> > On Nov 1, 2015, at 8:05 PM, Brian P. Martin 
> <notifications@github.com> wrote:
> >
> > I'm not sure I quite follow your question, but I'll take a stab at
> > answering it.
> >
> > The T7850 doesn't have a web page, in that there's nothing there that's
> > presentable to normal user. The API is accessible via HTTP, however.
> > For example, when I visit the main "page" for it I receive:
> >
> > {"api_ver":5,"type":"residential"}
> >
> > I wrote the code based on the vendor's "ColorTouch Remote Control
> > Protocol
> > 
> <http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf 
> <http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf>>" 
>
> > document, which doesn't appear to be specific to any particular models.
> > Since the T5900 is a ColorTouch thermostat, I think my code should work
> > just as well there.
> >
> > -B.
> >
> >
> > On 11/01/2015 06:46 PM, hplato wrote:
> > > Good points. I’d suggest we leave as is for the v4 release (since the
> > > window is short), but this could be a good task for the v4.1 update.
> > >
> > > As an aside, does the T7850 have the local web server option? I 
> wonder
> > > if it works with the T5900 module I put together. I’ve been using it
> > > successfully to control humidity, track state, turn schedules on 
> and off…
> > >
> > >
> > > > On Nov 1, 2015, at 7:40 PM, Brian P. Martin
> > > <notifications@github.com <mailto:notifications@github.com>> wrote:
> > > >
> > > > I wrote a Perl module to interface with my Venstar Colortouch T7850
> > > thermostat's web interface. It works great outside of MH, but 
> wouldn't
> > > work when called from my MH code. It took me about a week and a half
> > > to track it down. It turns out that we've got some really old 
> versions
> > > of some Perl modules included with Misterhouse. They're particularly
> > > weak in the are of SSL connections (and in fact the API interface has
> > > changed between the version included in MH and the current version on
> > > CPAN). I resolved my problem by renaming the following directories in
> > > MH to add a ".orig" suffix -- all are in lib/site:
> > > >
> > > > HTML
> > > > HTTP
> > > > LWP
> > > > LWP.pm
> > > > NET
> > > > URI
> > > >
> > > > This allowed me to use the more current versions on the system to
> > > set up an SSL connection to the Venstar web interface. I didn't 
> change
> > > any MH code, so MH on my system is now using the newer modules, too.
> > > I've seen no impact at all to MH, although I don't use the web
> > > interface a lot.
> > > >
> > > > What are our options for removing these from the Git tree and
> > > letting MH and any user code in it find the versions in the regular
> > > system Perl libraries? If we can't do that, how about renaming the 
> old
> > > versions (e.g. MHHTML, MHLWP) and making the matching adjustments in
> > > the MH code, so that user code running in MH that needs more current
> > > versions can access them, and MH can still use the old versions?
> > > >
> > > > Thank you for considering this.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > <https://github.com/hollie/misterhouse/issues/553 
> <https://github.com/hollie/misterhouse/issues/553>>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367>>.
> > >
> >
> >
> > --
> > --------------------
> > Brian P. Martin, Chief Consultant
> > Martin Consulting Services, Inc.
> > Phone: 503-617-4500
> > E-mail: Brian@MartinConsulting.com <mailto:Brian@martinconsulting.com>
> > Web: www.martinconsulting.com <http://www.martinconsulting.com/>
> > Blog: www.pdxsys.com <http://www.pdxsys.com/>
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152898383>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152905947>.
>


-- 
--------------------
Brian P. Martin, Chief Consultant
Martin Consulting Services, Inc.
Phone: 503-617-4500
E-mail: Brian@MartinConsulting.com
Web: www.martinconsulting.com
Blog: www.pdxsys.com

**Comment by hplato** [comment]
The local server (at least for the T5900) doesn’t require SSL?

**Comment by bpmartin20** [comment]
SSL is optional on mine, but given where it lives on the network, I 
wanted to use SSL.

             -B.

On 11/01/2015 08:45 PM, hplato wrote:
> The local server (at least for the T5900) doesn’t require SSL?
> > On Nov 1, 2015, at 9:27 PM, Brian P. Martin 
> <notifications@github.com> wrote:
> >
> > I looked at your module, but didn't try it out because it didn't appear
> > to support SSL. From what I saw of it, though, it's a lot better code
> > than mine.
> >
> > -B.
> >
> > On 11/01/2015 08:00 PM, hplato wrote:
> > > Yes, similar to my T5900. I’m just curious if that module I developed
> > > works with a later version. I set this up to access the local web
> > > server as I didn’t want to rely on the external ‘sky port’ cloud 
> service.
> > >
> > > The T5900 is api level 4, so I don’t know if that changes anything.
> > > For example my user user code:
> > >
> > > use Venstar_Colortouch;
> > >
> > > $thermostat_main = new Venstar_Colortouch(‘123.123.123.123',10);
> > > $thermostat_main_temp = new Venstar_Colortouch_Temp($thermostat_main);
> > > $thermostat_main_fan = new Venstar_Colortouch_Fan($thermostat_main);
> > > $thermostat_main_schedule = new
> > > Venstar_Colortouch_Schedule($thermostat_main);
> > > $thermostat_main_hum = new 
> Venstar_Colortouch_Humidity($thermostat_main);
> > > $thermostat_main_hum_sp = new
> > > Venstar_Colortouch_Humidity_sp($thermostat_main);
> > > $thermostat_main_comm = new Venstar_Colortouch_Comm($thermostat_main);
> > >
> > > I get these details when I start up MH:
> > >
> > > 0/17/15 02:30:34 PM [Venstar Colortouch] Residental Venstar 
> ColorTouch
> > > found with api level 4
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Data Successfully 
> Retrieved
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Device Main is a
> > > heating only Thermostat
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Fan mode is set to auto
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Fan is currently off
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System mode is heating
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is idle
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is on a schedule
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System schedule is day
> > > (occupied2)
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] System is currently on
> > > home mode
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current 
> Temperature: 23.5C
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Humidity:30%
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Setpoint 
> Min Max
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Heat: 22C 1.5C 37C
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Cool: 29.5C 1.5C 37C
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Humidity: 40%
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Setpoint Delta: 2C
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Thermostat
> > > Sensor Temperature:23.5C
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Current Thermostat
> > > Sensor Humidity:30%
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Outdoor Temperature
> > > Sensor not connected
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering temp child
> > > object
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering fanstate
> > > child object
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering sched 
> child
> > > object
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering hum child
> > > object
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering hum_sp
> > > child object
> > > 10/17/15 02:30:34 PM [Venstar Colortouch:Main] Registering comm child
> > > object
> > >
> > >
> > > > On Nov 1, 2015, at 8:05 PM, Brian P. Martin
> > > <notifications@github.com <mailto:notifications@github.com>> wrote:
> > > >
> > > > I'm not sure I quite follow your question, but I'll take a stab at
> > > > answering it.
> > > >
> > > > The T7850 doesn't have a web page, in that there's nothing there 
> that's
> > > > presentable to normal user. The API is accessible via HTTP, however.
> > > > For example, when I visit the main "page" for it I receive:
> > > >
> > > > {"api_ver":5,"type":"residential"}
> > > >
> > > > I wrote the code based on the vendor's "ColorTouch Remote Control
> > > > Protocol
> > > >
> > > 
> <http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf 
> <http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf> 
>
> > > 
> <http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf 
> <http://developer.venstar.com/assets/ColorTouchRemoteControlAPIv3rev1.pdf>>>" 
>
> > >
> > > > document, which doesn't appear to be specific to any particular 
> models.
> > > > Since the T5900 is a ColorTouch thermostat, I think my code 
> should work
> > > > just as well there.
> > > >
> > > > -B.
> > > >
> > > >
> > > > On 11/01/2015 06:46 PM, hplato wrote:
> > > > > Good points. I’d suggest we leave as is for the v4 release 
> (since the
> > > > > window is short), but this could be a good task for the v4.1 
> update.
> > > > >
> > > > > As an aside, does the T7850 have the local web server option? I
> > > wonder
> > > > > if it works with the T5900 module I put together. I’ve been 
> using it
> > > > > successfully to control humidity, track state, turn schedules on
> > > and off…
> > > > >
> > > > >
> > > > > > On Nov 1, 2015, at 7:40 PM, Brian P. Martin
> > > > > <notifications@github.com <mailto:notifications@github.com> 
> <mailto:notifications@github.com <mailto:notifications@github.com>>> 
> wrote:
> > > > > >
> > > > > > I wrote a Perl module to interface with my Venstar 
> Colortouch T7850
> > > > > thermostat's web interface. It works great outside of MH, but
> > > wouldn't
> > > > > work when called from my MH code. It took me about a week and 
> a half
> > > > > to track it down. It turns out that we've got some really old
> > > versions
> > > > > of some Perl modules included with Misterhouse. They're 
> particularly
> > > > > weak in the are of SSL connections (and in fact the API 
> interface has
> > > > > changed between the version included in MH and the current 
> version on
> > > > > CPAN). I resolved my problem by renaming the following 
> directories in
> > > > > MH to add a ".orig" suffix -- all are in lib/site:
> > > > > >
> > > > > > HTML
> > > > > > HTTP
> > > > > > LWP
> > > > > > LWP.pm
> > > > > > NET
> > > > > > URI
> > > > > >
> > > > > > This allowed me to use the more current versions on the 
> system to
> > > > > set up an SSL connection to the Venstar web interface. I didn't
> > > change
> > > > > any MH code, so MH on my system is now using the newer 
> modules, too.
> > > > > I've seen no impact at all to MH, although I don't use the web
> > > > > interface a lot.
> > > > > >
> > > > > > What are our options for removing these from the Git tree and
> > > > > letting MH and any user code in it find the versions in the 
> regular
> > > > > system Perl libraries? If we can't do that, how about renaming 
> the
> > > old
> > > > > versions (e.g. MHHTML, MHLWP) and making the matching 
> adjustments in
> > > > > the MH code, so that user code running in MH that needs more 
> current
> > > > > versions can access them, and MH can still use the old versions?
> > > > > >
> > > > > > Thank you for considering this.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/hollie/misterhouse/issues/553 
> <https://github.com/hollie/misterhouse/issues/553>
> > > <https://github.com/hollie/misterhouse/issues/553 
> <https://github.com/hollie/misterhouse/issues/553>>>.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367>
> > > 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152896367>>>.
> > > > >
> > > >
> > > >
> > > > --
> > > > --------------------
> > > > Brian P. Martin, Chief Consultant
> > > > Martin Consulting Services, Inc.
> > > > Phone: 503-617-4500
> > > > E-mail: Brian@MartinConsulting.com 
> <mailto:Brian@martinconsulting.com> <mailto:Brian@martinconsulting.com 
> <mailto:Brian@martinconsulting.com>>
> > > > Web: www.martinconsulting.com <http://www.martinconsulting.com/> 
> <http://www.martinconsulting.com/ <http://www.martinconsulting.com/>>
> > > > Blog: www.pdxsys.com <http://www.pdxsys.com/> 
> <http://www.pdxsys.com/ <http://www.pdxsys.com/>>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152898383 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152898383>>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152905947 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152905947>>.
> > >
> >
> >
> > --
> > --------------------
> > Brian P. Martin, Chief Consultant
> > Martin Consulting Services, Inc.
> > Phone: 503-617-4500
> > E-mail: Brian@MartinConsulting.com <mailto:Brian@martinconsulting.com>
> > Web: www.martinconsulting.com <http://www.martinconsulting.com/>
> > Blog: www.pdxsys.com <http://www.pdxsys.com/>
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152909739>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hollie/misterhouse/issues/553#issuecomment-152911324>.
>


-- 
--------------------
Brian P. Martin, Chief Consultant
Martin Consulting Services, Inc.
Phone: 503-617-4500
E-mail: Brian@MartinConsulting.com
Web: www.martinconsulting.com
Blog: www.pdxsys.com

**Comment by hplato** [comment]
To resurrect an old issue, I've made significant improvements in v2 of the module. It now uses a process item and get_url so that all the data transfer is backgrounded, removing the pauses. it looks like get_url doesn't support https, however that might be straightforward to add?

**Comment by hollie** [comment]
Hello @hplato,

I tried adding a test to do a POST request over HTTPS in Travis. See #661. Seems to work fine for recent Perls, but for one reason or the other failed on Perl 5.08. 

What are you testing that fails over HTTPS?

Regards,
 Lieven.

**Comment by hplato** [comment]
Actually I was mistaken with the above post. I tried get_url https://www.google.com and it works, so I think get_url does has SSL support in it. 

I have a old fedora box with Perl 5.8.8 on it. I can do a get_url https://www.google.com and it fetches data?

**Comment by hollie** [comment]
Hmm, not sure why it failed on Travis, I'm not sure if it is related to the Perl 5.08 version or something else.

**Comment by bpmartin20** [comment]
Getting back to the original topic ... MH contains some really old versions of Perl modules.  I think it's reasonable for MH to have pre-reqs that need to be installed when installing it, but more knowledgeable folks want it to "just work" out of the box (e.g. ship these modules with the installation package).  As a compromise what about this:

1. Have all Perl/CPAN modules that are going to be packaged with MH placed in a specific directory, separate from any of MH's own code (this may already be the case).
2. Add that directory at the _end_ of @INC, so those versions only get used if the same modules aren't already present in the normal Perl search path (system libraries, user's CPAN-installed modules, etc.).

That would still let MH work out of the box, but would let newer versions of the module preempt what is shipped with MH.  It also would have given me a legitimate way to use newer modules.  As it was, my solution was to delete the ones supplied by MH, and then hope I remembered to do it again with each new installation or update.

**Comment by hplato** [comment]
Just responding to this, Brian the latest venstar_colortouch on my github supports an ssl option. I’d be interested to see if it works for you. The background process_item model seems to be working well, I’ve had no pauses at all.
