### ISSUE TITLE
Maximum number devices.

### ISSUE THREAD

**Issue by sponnapalli** [hollie/misterhouse#609]
Hello, I am using amazon-Echo-HA-Bridge. I have 30 devices in the house. 28 devices work fine. As soon as I add a 29th device, Alexa stops detecting devices. Not sure where the problem is. I want to know is, is there a limit on the number of devices that this Bridge supports? Do I need to run two instances of this bridge on separate systems?  Please help.

Srikanth.

**Comment by hollie** [comment]
Hey @sponnapalli 

this is the repository of MisterHouse, and we can interface to the Echo bridge but we don't offer support for that software. For support questions on the bridge software, you better ask the question [here](https://github.com/armzilla/amazon-echo-ha-bridge).

Kind regards,
 Lieven.
