### ISSUE TITLE
NOAA website changes broke lib/site/Geo/WeatherNOAA.pm and get_weather

### ISSUE THREAD

**Issue by marcmerlin** [hollie/misterhouse#631]
gargamel:/var/local/src/misterhouse# mh/bin/get_weather -zone "SAN JOSE" -city "SAN JOSE" -state CA

Getting the current weather for SAN JOSE, CA
Getting the forecast for SAN JOSE, CA

Current conditions: No data available
## The forecast is As of :

Sadly, having a quick look at lib/site/Geo/WeatherNOAA.pm is not encouraging. Not knowing what the old page (that's now a redirect) looks like, it's hard to tell if it's gone altogether, or whether it's hiding under another URL and the fix is easy-ish.

**Comment by marcmerlin** [comment]
https://github.com/hollie/misterhouse/pull/629 (and its cleaned up replacement) make this work again, but the syntax of what you should query, has changed.
mh/bin/get_weather -zone MTR -city "SAN JOSE" -state CA

**Comment by klier** [comment]
This looks fixed to me.

**Comment by marcmerlin** [comment]
It is indeed fixed, thanks.

**Comment by ricks03** [comment]
Note that the NOAA has shutdown that (new, different, fixed) site:
"The site which previously served that data has been shut down. Here is a link where you can get similar data: http://forecast.weather.gov/product.php?site=RAH&issuedby=RAH&product=RWR&format=txt&version=1&glossary=0. Let me know if you have any questions."
