### ISSUE TITLE
ia7 slider does not work on android

### ISSUE THREAD

**Issue by tobser** [hollie/misterhouse#715]
On my Android devices it is not possible to grab the slider handle and move it to the desired value, you have to directly tab the slider bar at the target value. This makes it really difficult to set the correct value.

Tested with Firefox, Googlechrome and the lineageos browser

**Comment by hplato** [comment]
Thanks Tobi. Interesting, it now doesn't work on ios either, although at one point in the development it did. I have an andoid tablet that i can use to test.

**Comment by hplato** [comment]
I enabled ui.touch-punch and sliders now work on my IOS device. Can you try my IA7 branch to see if that fixes the Android problem (my tablet is charging…)

**Comment by tobser** [comment]
thanks, your fix works on all my browsers :-)
