### ISSUE TITLE
[SCHEDULE] logging every new minute

### ISSUE THREAD

**Issue by tobser** [hollie/misterhouse#733]
https://github.com/hollie/misterhouse/blob/a5ee7bab74666169f3569e1b8a2c212a3ca3c3d5/lib/Generic_Item.pm#L2001

Could we either comment this line or prevent it with if $::Debug{schedule} or something?
It creates log messages every minute.

Greetings
Tobi

**Comment by hplato** [comment]
I think this is fixed in master:

        ::print_log( "[SCHEDULE] - DEBUG - Checking schedule for ".$self->get_object_name." State is ".( state $self)." Child object is ".$object->get_object_name ) if $main::Debug{'schedule'};

**Comment by tobser** [comment]
Sorry if I was not clear about this, but I m referring to Generic_Item.pl not SCHEDULE.pm

**Comment by hplato** [comment]
I think Wayne fixed this, but right it isn't in hollie/master but rather in my hplato/ia7 branch that's being used to test out the http/1.1 overhaul. It will be fixed in the next release:

        for my $index ( 1 .. $self->{'schedule_count'} ) {
            if ( defined( $self->{ 'schedule_' . $index } ) ) {
                ::print_log( "[SCHEDULE] Checking time for "
                      . $self->get_object_name
                      . " schedule is "
                      . $self->{ 'schedule_' . $index }
                      . " time_cron return "
                      . &main::time_cron( $self->{ 'schedule_' . $index } ) )
			if $main::Debug{'schedule'};

**Comment by hplato** [comment]
I'm reopening this issue, it's actually closed, but I'm wondering if you might want to help out with those pesky floorplan icons. I've been trying a few different things, but still have icons jumping around. Can't figure out how to hide them until the 500ms refresh.

**Comment by tobser** [comment]
I'll have another look at the floorplan issues. But i can't promise anything, I too have already tried a lot stuff...

**Comment by hplato** [comment]
Sounds good. It seems like at first startup, (ie clear cache hard reload), the icons are below the image and then 400ms later they land in the perfectly arranged spot. I was trying to hide them until a refresh, but without luck. I probably noticed it more since I was making a bunch of changes to IA7 to I reload lots.

Lots of changes in 1.6 - sliders, dynamic tagline & load status, dynamic weather, cookie support for mode
