### ISSUE TITLE
Need help with install

### ISSUE THREAD

**Issue by 344Clinton** [hollie/misterhouse#792]
Hello. Trying to install MH on my new raspberry Pi. I'm have trouble running MH. Getting many errors about Dependancies. I tried installing the stuff via can, but no luck. Is there any new install guides? Should I be looking somewhere else other than sourcforge for install guides?

Craig

**Comment by doucga** [comment]
Have you come across this guide?

https://github.com/hollie/misterhouse/wiki/Raspberry-Pi

Garry

**Comment by hollie** [comment]
I've done some initial edits to the page to restore most of the formatting that got lost when porting the wiki to GitHub. 

I've also made some small changes to update the page content.

@344Clinton if you encounter issues when following the guide, feel free to make some edits to the page to bring it in line with your experiences.

Best regards,
 Lieven

**Comment by 344Clinton** [comment]
Hi Hollie. 
I got it working by running sudo CPAN, and then "install Switch" and "install Net::MQTT" ([mqtt](https://github.com/hollie/misterhouse/wiki/MQTT-interface))
