### ISSUE TITLE
ia7 cannot display group when state value of a member is a number

### ISSUE THREAD

**Issue by rob-vh** [hollie/misterhouse#852]
I have EIB5 thermometers, the receive_msg method returns a number, so the state value of EIB5 Items are numbers.  I also have thermometers that return string values.
With ia7, groups that have EIB5 thermometers do not open when you click them.  All other groups open fine.
I looked in the firefox console and saw javascript error "toLowerCase is not a function".  It turns out that ia7 sets the color of buttons based on the string value of the state value:

web/ia7/include/javascript.js
var getButtonColor = function (state) {
        var color = "default";
        if (state !== undefined) {
            state = state.toLowerCase();
        } else {
            return "purple";
        }
This obviously bombs when state is a number, so I inserted toString() and now both thermometer types work again.
            state = state.toString().toLowerCase();

Funny story, I ran mh 5.0 (stable branch) on an lubuntu 14.04 since 2017, and did not have this issue.  I installed xubuntu 22.04 this weekend, with the same /opt/misterhouse and /home/misterhouse directories, and the js errors started.  So it would seem js has _improved_ in those 5 (or 8?) years to flag down toLowerCase on Floats.  Bummer.  
As an initial fix I refreshed the /opt/misterhouse with git clone -b master, but that didn't solve it.  But inserting toString() does.

**Comment by rob-vh** [comment]
[852.diff.txt](https://github.com/hollie/misterhouse/files/9492003/852.diff.txt)

**Comment by hplato** [comment]
Added fix!
